### ISSUE TITLE
Foxbrowser forgets sync info on quit

### ISSUE THREAD

**Issue by Morac2** [graetzer/Foxbrowser#1]
Connecting Foxbrowser to Firefox Sync works fine, but every time the iPad app exits (quit, not just suspend), it forgets the Sync credentials.   As such every time I run it, it asks me to log in to sync. If I cancel, it simply won't sync. This is very inconvenient.

**Comment by graetzer** [comment]
I am investigating this problem, a workaround is to delete and reinstall the App.

**Comment by graetzer** [comment]
Probably won't fix any time soon. 
I really don't know why this still happens. I will rewrite the backend code that causes this for the Sync API 2.0 in a few months
