### ISSUE TITLE
Fox browser will not stay open

### ISSUE THREAD

**Issue by pgf102** [graetzer/Foxbrowser#12]
All of a sudden the Fox Browser will not open when I select it. It will open for a couple seconds then it will close.
It worked well originally when I installed it but not now.
I am using iPad ver. 5.1.1
Thanks 
Paul

**Comment by graetzer** [comment]
Yes, I think I know the problem, but unfortunately the Apple doesn't accept updates until the 28. December

**Comment by pgf102** [comment]
OK, thanks for your quick reply, I appreciate it.
Paul

On Dec 21, 2013, at 3:44 PM, Simon Grätzer notifications@github.com wrote:

> Yes, I think I know the problem, but unfortunately the Apple doesn't accept updates until the 28. december
> 
> —
> Reply to this email directly or view it on GitHub.

---

Dr. Paul Fehrenbach
Senior Instructor - Music
Penn State Univ. - DuBois
pgf102@gmail.com

## http://www2.ds.psu.edu/faculty/fehrenbach

**Comment by graetzer** [comment]
Does is work for you now?

**Comment by Mr-Mac** [comment]
Yes, thanks, it is working fine now. 

-----Original Message-----

**Comment by pgf102** [comment]
Yes it is working fine. Thanks for your concern,
Paul

On Tuesday, January 7, 2014, Simon Grätzer wrote:

> Does is work for you now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/graetzer/Foxbrowser/issues/12#issuecomment-31788613
> .

## 

---

Paul Fehrenbach, Ph.D.
Music & Integrated Arts
Penn State DuBois Campus
1 College Place

## DuBois, PA 15801
