### ISSUE TITLE
Update for iOS 7

### ISSUE THREAD

**Issue by toonetown** [graetzer/Foxbrowser#13]
Are the changes that make the app more iOS 7-like (styling, disappearing address bar, etc) going to be merged in to the repo?

**Comment by graetzer** [comment]
Not in the near feature. A few people build their own app's based on this code, but no one ever bothered to contribute any improvements. 
I put a lot of work in the iOS7 version and there is absolutely no benefit for me, by releasing it for free.

Of course if you're interested, you can contact me and we can work something out.
