### ISSUE TITLE
Crash immediately upon opening

### ISSUE THREAD

**Issue by krwudtke** [graetzer/Foxbrowser#14]
As soon as I open the app, it immediately closes. I tried uninstalling and reinstalling, and the app opens and allows sync to be setup, but then closes after configuration. Any suggestions?

**Comment by graetzer** [comment]
What device and which version of iOS are you using?

Could you send me the crash log? They are transferred to your computer when you connect your device to iTunes.
Mac OS X :  ~/Library/Logs/CrashReporter/MobileDevice/
Windows XP:  C:\Documents and Settings\Application Data\Apple computer\Logs\CrashReporter/
Windows 7:   C:\Users\AppData\Roaming\Apple computer\Logs\CrashReporter/MobileDevice/
