### ISSUE TITLE
new version of mozilla Sync 

### ISSUE THREAD

**Issue by erixtekila** [graetzer/Foxbrowser#15]
Hi,

I wonder if this project will be able toi sync with the new version of mozilla sync ?
https://support.mozilla.org/en-US/kb/how-to-update-to-the-new-firefox-sync?redirectlocale=en-US&as=u&redirectslug=how-sync-works-old-version-firefox&utm_source=inproduct
Thanks

**Comment by samer** [comment]
:+1: 
It would be great if it does.

**Comment by Zeyina** [comment]
No. Its not working with the new version of mozilla sync. 
Iphone is giving the passcode but you can't add a device anymore in the pc version of FF sync.  :( :-1:

**Comment by graetzer** [comment]
That's unfortunate.
I'm gonna release  a new version as soon as I can.

**Comment by adamprocter** [comment]
would be great if it can be 2 way now ?

**Comment by graetzer** [comment]
I'll do my best

**Comment by samer** [comment]
@graetzer, that's great news. Thanks a lot for your work!

**Comment by Zeyina** [comment]
Ohhh thats very nice @ graetzer. You made my day. Thank you so much

**Comment by gitgetgot** [comment]
Great to read, that Sync2 maybe will come :-)
Until then it would be very nice, if texts in iStore or on the FoxBrowser WebSite could be updated, so that users know, that this little piece of software isnt working as expected. I've searched my *rse off to find this thread here....

**Comment by allykzam** [comment]
+1 to @gitgetgot's comment, I just spent 15 minutes searching for how to get FF 31 to do the "Add Device" as instructed only to find out FF sync had changed in 29. (I've been on Chrome for a while)

**Comment by Zeyina** [comment]
Is there any hope for an update soon? I really miss this app so much

**Comment by Gilles92F** [comment]
+1.
I do support too your Project for Foxbrowser to become compatible with new Firefox sync. So, Firefox bookmarks would stay available on iPhone. 
Gilles, Paris (France)

**Comment by graetzer** [comment]
New version is in review
