### ISSUE TITLE
Email Address not accepted

### ISSUE THREAD

**Issue by PaulJHaag** [graetzer/Foxbrowser#16]
my email address looks like "nnnnn@nnn-nn.nnn" and is not accepted in the Foxbrowser iOS App version 3.0 on iOS 8.1.1

**Comment by graetzer** [comment]
That's indeed an oversight. That's what I get for copy&pasting an email regex from somewhere.
The commit 89e4cdc5a95be1c9e3221776031c3d0b5e56be2d fixes this issue and version 3.0.1 should hit the AppStore in about 6-8 days.
