### ISSUE TITLE
Crash on launch after setting up sync

### ISSUE THREAD

**Issue by adamprocter** [graetzer/Foxbrowser#17]
Latest version of the app on latest ios (ipad mini retina and iphone 5s) crash after setting up sync on launch. 
here is crash report from iPhone5s

https://www.dropbox.com/s/z8wb0zonfzn7jyi/foxcrash.zip?dl=0

**Comment by graetzer** [comment]
Should be fixed in version 3.0.2

**Comment by adamprocter** [comment]
Fantastic I can't wait.
Will it 2 way sync everything including history ?

**Comment by graetzer** [comment]
yes it does sync 2 way's

**Comment by adamprocter** [comment]
That is fantastic ! 
If the update is all that is promised, full 2 way sync, I will most certainly be donating to this project. Thanks again for your work on it.

**Comment by adamprocter** [comment]
Over Excited has update been submitted to App Store yet :)

**Comment by graetzer** [comment]
yes the status is Waiting For Review
