### ISSUE TITLE
I'd like a new icon… 

### ISSUE THREAD

**Issue by eutampieri** [graetzer/Foxbrowser#18]
I really like your app because of Firefox Sync, which I think it's really useful because it can replace Google Chrome and it works on all the devices I own, but I think the icon is horrible(please don't be angry with me: I know that designing an icon is really difficult). I know you can't use Firefox's icon but please check if you can use Iceweasel's one and out an acknowledgment in settings app like Apple does.
Good bye!

**Comment by eutampieri** [comment]
Sorry if I wrote that in issues, bat I'm really new to GitHub.

**Comment by graetzer** [comment]
Yeah it's pretty ugly, but I can't just completely change it now, it would confuse users.

**Comment by tomasz6000** [comment]
For me it looks pretty good.

**Comment by eutampieri** [comment]
Thank you!
Ok, I'll wait.
Happy new year,

Eugenio Tampieri
