### ISSUE TITLE
Browser susceptible to FREAK attack

### ISSUE THREAD

**Issue by sorenweber** [graetzer/Foxbrowser#27]
Testing against https://freakattack.com/ shows that foxbrowser is susceptible. More info on the bug at http://arstechnica.com/security/2015/03/freak-flaw-in-android-and-apple-devices-cripples-https-crypto-protection/ and the above site.

**Comment by graetzer** [comment]
All iOS browsers are vulnerable, because all iOS browsers depend on UIWebView/WKWebView as browser engine.
It's up to Apple to provide a bugfix for all devices. Unfortunately I can't disable the RSA_EXPORT cypher suite.
