### ISSUE TITLE
Manual Server Config Labels Misaligned with Textfields

### ISSUE THREAD

**Issue by AdamSulesky** [graetzer/Foxbrowser#3]
During custom server setup the 'Server URL' and 'Use Custom Server' labels are not across from their corresponding textfields and toggle.

'Server URL' label is across from boolean toggle
'Use Custom' Server is across from textfield

should have
'Server URL' label across from textfield
'Use Custom' Server across from boolean toggle 

Using IPad app
Version 1.6 on Apple Store

**Comment by graetzer** [comment]
Fixed in master
