### ISSUE TITLE
Custom Server Fails to Pair Device

### ISSUE THREAD

**Issue by AdamSulesky** [graetzer/Foxbrowser#4]
While attempting to pair Foxbrowser on an IPad with a custom server configuration I receive confirmation the pairing passcode has been successful and the device is paired within Mozilla Firefox browser interface.  Foxbrowser then presents a 'Login Failure   Incorrect Password' dialog.

If I then create a manual configuration, I also get the Login failure due to an incorrect password.

Foxbrowser version: 1.5
Server: myCloud Installation

My hunch is that my password length of 17 characters is being truncated.  I have not yet attempted to create a test account with a shorter password.

**Comment by graetzer** [comment]
Thanks I never noticed this. 
I just fixed this on the master branch. The next version should work correct
