### ISSUE TITLE
Foxbrowser Crashes on iPad2

### ISSUE THREAD

**Issue by chinkle214** [graetzer/Foxbrowser#5]
I just installed Fx on my iPad IOS 6.  I set up syncing on my MacBook. 

Fx wont open.  It opens and immediately closes.

**Comment by graetzer** [comment]
Could you submit the crash report from your device?
You can do that through iTunes

**Comment by chinkle214** [comment]
How do I do that?

Curt Hinkle
Area Director / Regional Trainer 
Young Life Elk River/Rogers 
PO Box 614
Elk River, MN  55330 
C: 612.598.2685
www.elkriver.younglife.org

**Comment by graetzer** [comment]
iTunes copies crash reports to your computer and stores them:
Mac OS X : ~/Library/Logs/CrashReporter/MobileDevice/
Windows XP: C:\Documents and Settings\Application Data\Apple computer\Logs\CrashReporter/
Windows Vista: C:\Users\AppData\Roaming\Apple computer\Logs\CrashReporter/MobileDevice/
Theoretically they are submitted automatically

Am 04.02.2013 um 19:12 schrieb chinkle214 notifications@github.com:

**Comment by chinkle214** [comment]
I just did a sync of my iPad through iTunes.  The CrashReporter is empty (Mac OX)

Curt Hinkle
Area Director / Regional Trainer 
Young Life Elk River/Rogers 
PO Box 614
Elk River, MN  55330 
C: 612.598.2685
www.elkriver.younglife.org

**Comment by graetzer** [comment]
I discovered and fixed the bug that most likely causes the crash. The updated version (2.0.3) of Foxbrowser should be available next week.

Am 08.02.2013 um 15:58 schrieb chinkle214 notifications@github.com:

**Comment by chinkle214** [comment]
OK, thanks!

Curt Hinkle
Area Director / Regional Trainer 
Young Life Elk River/Rogers 
PO Box 614
Elk River, MN  55330 
C: 612.598.2685
www.elkriver.younglife.org
