### ISSUE TITLE
Foxbrowser hangs on clean launch

### ISSUE THREAD

**Issue by ryu2** [graetzer/Foxbrowser#6]
Downloaded the latest from github, and built it in XCode.

When I launch, the dialog to pair with Firefox Sync comes up, I enter the code, and it seems to work OK.  However, when I enter anything in the URL/search bar afterwards, the app hangs.

The relevant call stacks seem to be:
#0  0x9b5edd12 in syscall_thread_switch ()
#1  0x01e24248 in _objc_rootRetain_slow ()
#2  0x01e23db5 in _objc_rootRetain ()
#3  0x0209f393 in -[NSObject retain]()
#4  0x01e23d30 in objc_retain ()
#5  0x00013b79 in +[SGWebViewController initialize] at /Users/ryu2/git/Foxbrowser/Foxbrowser/Common/WebView/SGWebViewController.m:48
#6  0x01e11641 in _class_initialize ()
#7  0x01e184c6 in prepareForMethodLookup ()
#8  0x01e0f914 in lookUpMethod ()
#9  0x01e0fac5 in class_getMethodImplementation ()
#10 0x01e23c51 in arr_read_weak_reference ()
#11 0x01e240f4 in objc_loadWeakRetained ()
#12 0x01e2411c in objc_loadWeak ()
#13 0x00006abc in -[SGTabView setViewController:] at /Users/ryu2/git/Foxbrowser/Foxbrowser/iPad/SGTabView.m:87
#14 0x0000d844 in __54-[SGTabsViewController swapCurrentViewControllerWith:]_block_invoke at /Users/ryu2/git/Foxbrowser/Foxbrowser/iPad/SGTabsViewController.m:232
#15 0x00fae886 in __86+[UIView(Internal) _transitionFromView:toView:duration:options:animations:completion:]_block_invoke_01080 ()
#16 0x00fad79c in -[UIViewAnimationBlockDelegate _sendDeferredCompletion:]()
#17 0x0189985d in __NSFireDelayedPerform ()
#18 0x02071936 in **CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** ()
#19 0x020713d7 in __CFRunLoopDoTimer ()
#20 0x01fd4790 in __CFRunLoopRun ()
#21 0x01fd3d84 in CFRunLoopRunSpecific ()
#22 0x01fd3c9b in CFRunLoopRunInMode ()
#23 0x0222f7d8 in GSEventRunModal ()
#24 0x0222f88a in GSEventRun ()
#25 0x00f73626 in UIApplicationMain ()
#26 0x00002dcd in main at /Users/ryu2/git/Foxbrowser/Foxbrowser/main.m:16
#27 0x00002cf5 in start ()
#0  0x9b5edc22 in mach_msg_trap ()
#1  0x9b5ed1f6 in mach_msg ()
#2  0x0207110a in __CFRunLoopServiceMachPort ()
#3  0x01fd45d5 in __CFRunLoopRun ()
#4  0x01fd3d84 in CFRunLoopRunSpecific ()
#5  0x01fd3c9b in CFRunLoopRunInMode ()
#6  0x000a20c8 in +[ASIHTTPRequest runRequests] at /Users/ryu2/git/Foxbrowser/External/asi-http-request/ASIHTTPRequest.m:4796
#7  0x018854d6 in -[NSThread main]()
#8  0x01885447 in **NSThread__main** ()
#9  0x98e52ed9 in _pthread_start ()
#0  0x01e24453 in objc_clear_deallocating ()
#1  0x01e19ff8 in objc_destructInstance ()
#2  0x01fa9913 in CFRelease ()
#3  0x01fb21b9 in CFURLCreateStringByReplacingPercentEscapes ()
#4  0x01fb184f in CFURLCreateStringByReplacingPercentEscapesUsingEncoding ()
#5  0x01fb17ae in URLPathToPOSIXPath ()
#6  0x01fa780a in CFURLCreateStringWithFileSystemPath ()
#7  0x01faaaf7 in CFURLGetFileSystemRepresentation ()
#8  0x02084eb1 in -[CFXPreferencesPropertyListSourceSynchronizer _backingPlistChangedSinceLastSync]()
#9  0x02085294 in -[CFXPreferencesPropertyListSourceSynchronizer synchronizeAlreadyFlocked]()
#10 0x02085561 in -[CFXPreferencesPropertyListSourceSynchronizer synchronize]()
#11 0x020848f5 in __79-[CFXPreferencesPropertyListSource synchronizeInBackgroundWithCompletionBlock:]_block_invoke_0 ()
#12 0x02622330 in _dispatch_call_block_and_release ()
#13 0x02623f0c in _dispatch_queue_drain ()
#14 0x02623cb4 in _dispatch_queue_invoke ()
#15 0x02623402 in _dispatch_worker_thread2 ()
#16 0x98e54b24 in _pthread_wqthread ()

**Comment by graetzer** [comment]
Should work now. This is a weird issue, there seems to be a death lock with the main thread
